---
# Source: stakater-checkov-scan/templates/task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stakater-checkov-scan
  labels:
    app.kubernetes.io/version: "1.0.0"
spec:
  workspaces:
    - name: source
  params:
    - name: BUILD_IMAGE
      description: Flag specifying whether image should be built again.
      default: 'true'
      type: string
  steps:
    - name: scan
      image: bridgecrew/checkov:3
      workingDir: $(workspaces.source.path)
      script: |
        if [[ $(params.BUILD_IMAGE) == true ]]; then
          checkov -d . -s
        fi
